basePath: /v1/api
definitions:
  core.Resp:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  dto.UserDto:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  dto.UserRegDto:
    properties:
      nickname:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  model.Menu:
    properties:
      icon:
        type: string
      id:
        type: integer
      label:
        type: string
    type: object
host: localhost:9999
info:
  contact: {}
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Swagger Example API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - description: 用户登录
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/dto.UserDto'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/core.Resp'
            - properties:
                code:
                  type: integer
                data:
                  type: string
                msg:
                  type: string
              type: object
      summary: 登录
      tags:
      - 登录
  /menus:
    get:
      consumes:
      - application/json
      description: 获取菜单
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/core.Resp'
            - properties:
                data:
                  $ref: '#/definitions/model.Menu'
              type: object
      summary: 菜单
  /register:
    post:
      consumes:
      - application/json
      description: 注册
      parameters:
      - description: 用户注册
        in: body
        name: dto.UserRegDto
        required: true
        schema:
          $ref: '#/definitions/dto.UserRegDto'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/core.Resp'
            - properties:
                code:
                  type: integer
                data:
                  type: string
                msg:
                  type: string
              type: object
      summary: 注册
      tags:
      - 注册
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
x-extension-openapi:
  example: value on a json format
